import { Grid } from 'components/Grid'
import { Layout } from 'components/Layout'
import { useAuth } from 'context/authContext'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import { getAlbums } from 'services/albums'

export default function Home() {
  const [albums, setAlbums] = useState([])
  console.log('🚀 ~ file: index.js ~ line 13 ~ Home ~ albums', albums)
  const { user, isLoading } = useAuth()
  const router = useRouter()
  console.log('🚀 ~ file: index.js ~ line 8 ~ Home ~ user', user)

  useEffect(() => {
    if (!isLoading && !user) {
      console.log('Theres no user :D')
      router.push('/login')
    }

    const fetchAlbums = async () => {
      const [data, error] = await getAlbums()
      setAlbums(data)
      if (error) {
        console.log(error)
      }
    }

    fetchAlbums()
  }, [isLoading, router, user])

  return (
    <div className='bg-zinc-900 text-white'>
      <Head>
        <title>Social Album | home </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Layout>
        <h1 className='text-2xl my-2'>All the albums :D</h1>

        <Grid>
          {albums.map((album) => (
            <Link key={album.id} href={`/album/${album.id}`}>
              <a className='py-2 px-4  bg-zinc-700 shadow-md shadow-zinc-700/50 rounded relative hover:bg-zinc-800 hover:shadow-zinc-700/90 hover:shadow-xl ease-in-out duration-150 min-h-[150px] w-full z-50'>
                {album.cover && (
                  <Image
                    src={album.cover}
                    layout='fill'
                    alt='image'
                    className='relative rounded'
                  />
                )}
                <div className='bg-[#00000070] absolute top-0 bottom-0 left-0 right-0 z-20 rounded'></div>
                {console.log(album, 'FROOOOOOM ALBUMS')}
                <h2 className='text-center z-40 font-bold absolute bottom-2'>
                  {album.name}
                </h2>
              </a>
            </Link>
          ))}
        </Grid>
      </Layout>
    </div>
  )
}
