import { Layout } from 'components/Layout'
import { useAuth } from 'context/authContext'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import { getAlbums } from 'services/albums'

export default function Home() {
  const [albums, setAlbums] = useState([])
  const { user, isLoading } = useAuth()
  const router = useRouter()
  console.log('🚀 ~ file: index.js ~ line 8 ~ Home ~ user', user)

  useEffect(() => {
    if (!isLoading && !user) {
      console.log('Theres no user :D')
      router.push('/login')
    }

    const fetchAlbums = async () => {
      const [data, error] = await getAlbums()
      setAlbums(data)
      if (error) {
        console.log(error)
      }
    }

    fetchAlbums()
  }, [isLoading, router, user])

  return (
    <div className='bg-zinc-900 text-white'>
      <Head>
        <title>Social Album | home </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Layout>
        <h1 className='text-2xl'>All the albums :D</h1>

        {albums.map((album) => (
          <Link key={album.id} href={`/album/${album.id}`}>
            <a>
              <h2>{album.name}</h2>
              <p>{album.description}</p>
            </a>
          </Link>
        ))}
      </Layout>
    </div>
  )
}
